### PR TITLE
Done : Removed alt text from Github Images

### PR DESCRIPTION
**Pull request by Supriya-shashivasan**
Removed all the alt texts from the github images

### CODE REVIEW

**Comment by nebrelbug** [comment]
I'm sorry, but unfortunately psycho5 asked if he could work on the issue first. Your code looks good other than that you deleted all of the image alt text, not just the Github images.

Thank you for your contribution though--I'll try and find some other issues that you could work on soon.

**Comment by nebrelbug** [comment]
@Supriya-shashivasan , would you be interested in helping with issue #9 ?

**Comment by nebrelbug** [comment]
Or @girishpatil ?

**Comment by Supriya-shashivasan** [comment]
Sure.. ll work on it

**Pull request closed without merging**
