### PR TITLE
Added comments to Compile.js

### PR DESCRIPTION
**Pull request by brendanpettis**
Check **all** applicable boxes below (put an x in between the square brackets)

- [x] This is to fix an issue. Issue #:
- [ ] If I modified anything other than comments, I ran `npm run build` and `npm test`

## Summary
This pull request makes it so...

### CODE REVIEW

**Comment by nebrelbug** [comment]
In the future, try and fill out the template 😄. For example, it's helpful to know that this closes #53.

**Comment by nebrelbug** [comment]
Thanks @brendanpettis! You are now... a Squirrelly contributor! 👏

**Comment by brendanpettis** [comment]
Thanks for letting me help, and for the feedback @nebrelbug!

**Comment by nebrelbug** [comment]
You're welcome!

**Pull request merged**
